from .models import Component

hierarchy = {
    Component.KIND_STREET_ADDRESS:  [Component.KIND_SUBPREMISE],
    Component.KIND_ROUTE:           [Component.KIND_NEIGHBORHOOD],
    Component.KIND_INTERSECTION:    [Component.KIND_NEIGHBORHOOD],
    Component.KIND_POLITICAL:       [Component.KIND_AAL5],
    Component.KIND_AAL1:            [Component.KIND_COUNTRY],
    Component.KIND_AAL2:            [Component.KIND_AAL1],
    Component.KIND_AAL3:            [Component.KIND_AAL2],
    Component.KIND_AAL4:            [Component.KIND_AAL3],
    Component.KIND_AAL5:            [Component.KIND_AAL4],
    Component.KIND_COLLOQUIAL_AREA: [Component.KIND_AAL5],
    Component.KIND_LOCALITY:        [Component.KIND_AAL5],
    Component.KIND_WARD:            [Component.KIND_AAL5],
    Component.KIND_SUBLOCALITY:     [Component.KIND_LOCALITY],
    Component.KIND_NEIGHBORHOOD:    [Component.KIND_SUBLOCALITY],
    Component.KIND_PREMISE:         [Component.KIND_NEIGHBORHOOD],
    Component.KIND_SUBPREMISE:      [Component.KIND_PREMISE],
    Component.KIND_POSTAL_CODE:     [Component.KIND_NEIGHBORHOOD],
    Component.KIND_NATURAL_FEATURE: [Component.KIND_NEIGHBORHOOD],
    Component.KIND_AIRPORT:         [Component.KIND_NEIGHBORHOOD],
    Component.KIND_PARK:            [Component.KIND_NEIGHBORHOOD],
    Component.KIND_POI:             [Component.KIND_NEIGHBORHOOD],
    Component.KIND_FLOOR:           [Component.KIND_SUBPREMISE],
    Component.KIND_ESTABLISHMENT:   [Component.KIND_SUBPREMISE],
    Component.KIND_PARKING:         [Component.KIND_SUBPREMISE],
    Component.KIND_POST_BOX:        [Component.KIND_POST_BOX],
    Component.KIND_POSTAL_TOWN:     [Component.KIND_SUBLOCALITY],
    Component.KIND_ROOM:            [Component.KIND_FLOOR],
    Component.KIND_STREET_NUMBER:   [Component.KIND_STREET_ADDRESS],
    Component.KIND_BUS_STATION:     [Component.KIND_STREET_NUMBER],
    Component.KIND_TRAIN_STATION:   [Component.KIND_STREET_NUMBER],
    Component.KIND_TRANSIT_STATION: [Component.KIND_STREET_NUMBER],
}
