# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='old_address',
            field=models.CharField(default=b'', max_length=1024),
        ),
    ]
