# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_example_old_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='address',
        ),
    ]
