# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 05:31
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_finalise_version_2'),
        ('example', '0003_remove_example_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
