# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_migrate_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='old_address',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
