# Generated by Django 3.1.2 on 2020-12-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
