# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_finalise_version_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
