# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='short_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
