# Generated by Django 2.0.3 on 2018-03-29 22:34

import address.models
import address.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', address.fields.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
